# SPDX-FileCopyrightText: 2025 crux contributors <https://github.com/ash-project/crux/graphs.contributors>
#
# SPDX-License-Identifier: MIT

name: Ash CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    permissions:
      contents: write
      pages: write
      id-token: write
      security-events: write
    with:
      release: true
      publish-docs: true
      spark-formatter: false
      codegen: false
      doctor: true
      conventional-commit: false
      spark-cheat-sheets: false
      sobelow: true
      postgres: false
      tenants: false
      reuse: true
      community-files: true
